[package]
name = "suki_no_konseki"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "app/svc-crm",
    "lib/common-config",
    "lib/common-db",
    "lib/common-misc",
    "lib/common-type",
    "lib/common-web",
    "lib/internal-clients",
    "migration/migration-crm",
]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.1.0"

[workspace.dependencies]
actix-web = "4"
actix-cors = "0.7"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "1", features = ["serde", "v4"] }
chrono = { version = "0.4", features = ["serde"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
log = "0.4"
env_logger = "0.11"

sea-orm = { version = "1.1", features = [
    "sqlx-postgres",
    "runtime-tokio-native-tls",
    "macros",
] }


utoipa = { version = "5", features = ["uuid", "chrono"] }
utoipa-actix-web = "0.1"
utoipa-swagger-ui = { version = "9", features = ["actix-web"] }
reqwest = { version = "0.12", features = ["json", "rustls-tls"] }
anyhow = "1"
thiserror = "1"

dotenvy = "0.15.7"
sea-orm-migration = "1.1.16"
argon2 = "0.5.3"

common-config = { path = "lib/common-config" }
common-db = { path = "lib/common-db" }
common-web = { path = "lib/common-web" }
common-type = { path = "lib/common-type" }
migration-crm = { path = "migration/migration-crm" }
internal-clients = { path = "lib/internal-clients" }
