[package]
name = "svc-crm"
version.workspace = true
edition.workspace = true

[dependencies]
common-config = { workspace = true }
common-db = { workspace = true }
common-web = { workspace = true }
common-type = { workspace = true }
common-grpc = { workspace = true }
internal-clients = { workspace = true }

actix-web = { workspace = true }
actix-cors = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
tokio = { workspace = true }
sea-orm = { workspace = true }
utoipa = { workspace = true }
utoipa-actix-web = { workspace = true }
utoipa-swagger-ui = { workspace = true }
log = { workspace = true }
dotenvy = { workspace = true }
argon2 = { workspace = true }
once_cell = { workspace = true }
# jsonwebtoken = { workspace = true }
tonic = { workspace = true }
prost = { workspace = true }
tonic-prost = { workspace = true }
migration-crm = { workspace = true }
