[package]
name = "svc-crm"
version.workspace = true
edition.workspace = true

[dependencies]
actix-web = { workspace = true }
actix-cors = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
tokio = { workspace = true }
sea-orm = { workspace = true }
utoipa = { workspace = true }
utoipa-actix-web = { workspace = true }
utoipa-swagger-ui = { workspace = true }
common-config = { workspace = true }
common-db = { workspace = true }
common-web = { workspace = true }
internal-clients = { workspace = true }
log = { workspace = true }
dotenvy = { workspace = true }

migration-crm = { path = "../../migration/migration-crm" }
