[package]
name = "common-grpc"
edition.workspace = true
version.workspace = true

[dependencies]
tonic = { workspace = true }
prost = { workspace = true }
tonic-prost = { workspace = true }
once_cell = { workspace = true }
tokio = { workspace = true }

[build-dependencies]
tonic-prost-build = { workspace = true }
