[package]
name = "svc-auth"
edition.workspace = true
version.workspace = true

[dependencies]
common-grpc = { workspace = true }
common-type = { workspace = true }
common-config = { workspace = true }
common-db = { workspace = true }
common-web = { workspace = true }

migration-auth = { workspace = true }

tokio = { workspace = true }
actix-web = { workspace = true }
utoipa = { workspace = true }
once_cell = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
jsonwebtoken = { workspace = true }
sea-orm = { workspace = true }
log = { workspace = true }
base64 = { workspace = true }
blake3 = { workspace = true }
rand = { workspace = true }
