//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.6

use common_type::EntityStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(schema_name = "crm", table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub ent_st: EntityStatus,
    #[sea_orm(unique)]
    pub username: String,
    #[sea_orm(unique)]
    pub email: Option<String>,
    pub phone: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub password_hash: String,
    pub display_name: Option<String>,
    pub role: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    #[sea_orm(column_type = "Text", nullable)]
    pub updated_reason: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_one = "super::user_profiles::Entity")]
    UserProfiles,
    #[sea_orm(has_many = "super::users_aud::Entity")]
    UsersAud,
}

impl Related<super::user_profiles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserProfiles.def()
    }
}

impl Related<super::users_aud::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UsersAud.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
