//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.6

use common_type::{AuditStatus, EntityStatus};
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(schema_name = "auth", table_name = "refresh_tokens_aud")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub aud_st: AuditStatus,
    pub ent_id: Option<Uuid>,
    pub ent_st: Option<EntityStatus>,
    pub prev_id: Option<Uuid>,
    pub user_id: Option<Uuid>,
    pub refresh_hash: Option<String>,
    pub ip_address: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub user_agent: Option<String>,
    pub exp: Option<DateTimeWithTimeZone>,
    pub iat: Option<DateTimeWithTimeZone>,
    pub is_revoked: Option<bool>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub created_by: Option<Uuid>,
    pub updated_at: Option<DateTimeWithTimeZone>,
    pub updated_by: Option<Uuid>,
    pub device_id: Option<String>,
    pub version: Option<String>,
    pub updated_reason: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::refresh_tokens::Entity",
        from = "Column::EntId",
        to = "super::refresh_tokens::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    RefreshTokens,
}

impl Related<super::refresh_tokens::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RefreshTokens.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
