//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.6

use common_type::EntityStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(schema_name = "auth", table_name = "refresh_tokens")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub ent_st: EntityStatus,
    pub prev_id: Option<Uuid>,
    pub user_id: Uuid,
    pub refresh_hash: String,
    pub ip_address: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub user_agent: Option<String>,
    pub exp: DateTimeWithTimeZone,
    pub iat: DateTimeWithTimeZone,
    pub is_revoked: bool,
    pub created_at: DateTimeWithTimeZone,
    pub created_by: Uuid,
    pub updated_at: Option<DateTimeWithTimeZone>,
    pub updated_by: Option<Uuid>,
    pub device_id: Option<String>,
    pub version: String,
    pub updated_reason: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::PrevId",
        to = "Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    SelfRef,
    #[sea_orm(has_many = "super::refresh_tokens_aud::Entity")]
    RefreshTokensAud,
}

impl Related<super::refresh_tokens_aud::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RefreshTokensAud.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
